=== mithrandir4859/projects/Task 3 XML/xml/deposit.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="ua.andrieiev.xml" xmlns:bank="ua.andrieiev.xml"
	elementFormDefault="qualified">

	<!-- Global root element -->
	<xs:element name="bank">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="xs:string" />
				<xs:element name="registration" type="bank:registration" maxOccurs="unbounded" />
				<xs:element name="accounts" type="bank:accounts" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<!-- Wrapper for accounts -->
	<xs:complexType name="accounts">
		<xs:sequence>
			<xs:element name="account" type="bank:account" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<!-- Now we have only one nested element in registration type, but further 
		extending is very likely -->
	<xs:complexType name="registration">
		<xs:sequence>
			<xs:element name="country" type="xs:string" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="account">
		<xs:sequence>

			<xs:element name="number" type="xs:long" />
			<xs:element name="type" type="bank:accountType" />
			<xs:element name="depositor" type="bank:person" />

			<xs:element name="balance">
				<xs:simpleType>
					<xs:restriction base="xs:decimal">
						<xs:totalDigits value="10" />
						<xs:fractionDigits value="2" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>

			<xs:element name="rate">
				<xs:simpleType>
					<xs:restriction base="xs:decimal">
						<xs:totalDigits value="4" />
						<xs:fractionDigits value="3" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>

			<xs:element name="dateStart" type="xs:date" />
			<xs:element name="dateEnd" type="xs:date" minOccurs="0" />

		</xs:sequence>
		<!-- <xs:attribute name="id" type="xs:positiveInteger" use="required" /> -->
	</xs:complexType>


	<xs:complexType name="person">
		<xs:sequence>
			<xs:element name="firstname" type="bank:name" />
			<xs:element name="lastname" type="bank:name" />
			<xs:element name="ssn" type="bank:SSN" />
		</xs:sequence>
		<xs:attribute name="id" type="xs:positiveInteger" use="required" />
	</xs:complexType>

	<xs:simpleType name="SSN">
		<xs:restriction base="xs:token">
			<xs:pattern value="[0-9]{3}-[0-9]{2}-[0-9]{4}" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="name">
		<xs:restriction base="xs:string">
			<xs:minLength value="2" />
			<xs:maxLength value="20" />
			<xs:pattern value="[A-Z][a-z]+" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="accountType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Poste restante" />
			<xs:enumeration value="Urgent" />
			<xs:enumeration value="Accumulative" />
			<xs:enumeration value="Metal" />
			<xs:enumeration value="Current" />
			<xs:enumeration value="Savings" />
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== mithrandir4859/projects/Task 3 XML/xml/bank.xml
<?xml version="1.0" encoding="UTF-8"?>
<b:bank xmlns:b="ua.andrieiev.xml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="ua.andrieiev.xml deposit.xsd ">
	<b:name>Renaissance Capital Bank Beijing</b:name>
	<b:registration>
		<b:country>China</b:country>
	</b:registration>

	<b:accounts>
		<b:account>
			<b:number>100500</b:number>
			<b:type>Poste restante</b:type>
			<b:depositor id="1">
				<b:firstname>Yurii</b:firstname>
				<b:lastname>Andrieiev</b:lastname>
				<b:ssn>333-22-4444</b:ssn>
			</b:depositor>
			<b:balance>6666.66</b:balance>
			<b:rate>0.124</b:rate>
			<b:dateStart>2002-09-08</b:dateStart>
			<b:dateEnd>2214-11-30</b:dateEnd>
		</b:account>

		<b:account>
			<b:number>100500</b:number>
			<b:type>Poste restante</b:type>
			<b:depositor id="2">
				<b:firstname>Duncan</b:firstname>
				<b:lastname>Davidson</b:lastname>
				<b:ssn>333-22-4444</b:ssn>
			</b:depositor>
			<b:balance>1000000.03</b:balance>
			<b:rate>0.124</b:rate>
			<b:dateStart>2002-09-08</b:dateStart>
			<b:dateEnd>2214-11-30</b:dateEnd>
		</b:account>

		<b:account>
			<b:number>100500</b:number>
			<b:type>Poste restante</b:type>
			<b:depositor id="3">
				<b:firstname>Kent</b:firstname>
				<b:lastname>Beck</b:lastname>
				<b:ssn>333-22-4444</b:ssn>
			</b:depositor>
			<b:balance>10006000.10</b:balance>
			<b:rate>0.124</b:rate>
			<b:dateStart>2002-09-08</b:dateStart>
			<b:dateEnd>2214-11-30</b:dateEnd>
		</b:account>

		<b:account>
			<b:number>100500</b:number>
			<b:type>Poste restante</b:type>
			<b:depositor id="4">
				<b:firstname>Joshua</b:firstname>
				<b:lastname>Bloch</b:lastname>
				<b:ssn>333-22-4444</b:ssn>
			</b:depositor>
			<b:balance>200000.32</b:balance>
			<b:rate>0.124</b:rate>
			<b:dateStart>2002-09-08</b:dateStart>
			<b:dateEnd>2214-11-30</b:dateEnd>
		</b:account>

		<b:account>
			<b:number>100500</b:number>
			<b:type>Poste restante</b:type>
			<b:depositor id="5">
				<b:firstname>Marc</b:firstname>
				<b:lastname>Fleury</b:lastname>
				<b:ssn>333-22-4444</b:ssn>
			</b:depositor>
			<b:balance>6666.66</b:balance>
			<b:rate>0.124</b:rate>
			<b:dateStart>2002-09-08</b:dateStart>
			<b:dateEnd>2214-11-30</b:dateEnd>
		</b:account>

		<b:account>
			<b:number>100500</b:number>
			<b:type>Poste restante</b:type>
			<b:depositor id="6">
				<b:firstname>Craig</b:firstname>
				<b:lastname>Mcclanahan</b:lastname>
				<b:ssn>333-22-4444</b:ssn>
			</b:depositor>
			<b:balance>314123.42</b:balance>
			<b:rate>0.124</b:rate>
			<b:dateStart>2002-09-08</b:dateStart>
			<b:dateEnd>2214-11-30</b:dateEnd>
		</b:account>

		<b:account>
			<b:number>100500</b:number>
			<b:type>Poste restante</b:type>
			<b:depositor id="7">
				<b:firstname>Rod</b:firstname>
				<b:lastname>Johnson</b:lastname>
				<b:ssn>333-22-4444</b:ssn>
			</b:depositor>
			<b:balance>3124.56</b:balance>
			<b:rate>0.124</b:rate>
			<b:dateStart>2002-09-08</b:dateStart>
			<b:dateEnd>2214-11-30</b:dateEnd>
		</b:account>

		<b:account>
			<b:number>100500</b:number>
			<b:type>Poste restante</b:type>
			<b:depositor id="8">
				<b:firstname>Gavin</b:firstname>
				<b:lastname>King</b:lastname>
				<b:ssn>333-22-4444</b:ssn>
			</b:depositor>
			<b:balance>432234.99</b:balance>
			<b:rate>0.174</b:rate>
			<b:dateStart>2002-09-08</b:dateStart>
			<b:dateEnd>2214-11-30</b:dateEnd>
		</b:account>

		<b:account>
			<b:number>100500</b:number>
			<b:type>Poste restante</b:type>
			<b:depositor id="9">
				<b:firstname>James</b:firstname>
				<b:lastname>Gosling</b:lastname>
				<b:ssn>333-22-4444</b:ssn>
			</b:depositor>
			<b:balance>7777774.43</b:balance>
			<b:rate>0.324</b:rate>
			<b:dateStart>2002-09-08</b:dateStart>
			<b:dateEnd>2214-11-30</b:dateEnd>
		</b:account>

	</b:accounts>
</b:bank>
